# to create from scratch: conda env create -f environment.yml
# to update the environment: conda env update --name myenv --file environment.yml --prune
# or update with environment activated: conda env update --file environment.yml --prune

name: ac
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9.2
  - pip
  - pip:
    # mkdocs core
    - mkdocs~=1.6
    - mkdocs-material==9.5.45
    - mkdocs-material-extensions~=1.3
    - markdown~=3.2
    - jinja2~=3.0
    - pygments~=2.16
    - pymdown-extensions~=10.2
    # mkdocs plugins
    - babel~=2.10
    - colorama~=0.4
    - paginate~=0.5
    - regex>=2022.4
    - requests~=2.26
    - mkdocs-minify-plugin~=0.5
    # cpp docs
    - ruamel.yaml~=0.18.6
    - mkdoxy~=1.2.6
    - mkdocs-glightbox~=0.4.0
    - mkdocs-open-in-new-tab~=1.0.8
    - mkdocs-git-revision-date-localized-plugin~=1.3.0
    - mkdocs-macros-plugin~=1.3.7


