name: changelog-build
on:
  release:
    types: [published]

jobs:
  changelog:
    name: Update changelog
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: main
    
      - name: Update changelog
        uses: rhysd/changelog-from-release/action@v3
        with:
            file: CHANGELOG.md
            github_token: ${{ secrets.GITHUB_TOKEN }}
            pull_request: true