name: doc-build

on:
  push:
    branches:
      - master
      - main
    paths:
      - 'tests/**'
      - 'src/**'
      - 'cmake/**'
      - 'CMakeLists.txt'
      - 'Dockerfile'
      - 'assets/**'
      - 'deps/**'
      - 'docs/**'
      - 'materials/**'
      - 'mkdocs.yml'
  workflow_dispatch: # allows manual trigger


jobs:
  build-doc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 


      - name: Install Doxygen
        run: sudo apt-get install -y doxygen

      - name: Setup conda environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          auto-update-conda: true
          python-version: 3.9.2

      - name: Replace the changelog/index.md with the latest CHANGELOG.md but convert it to UTF8
        run: iconv -f ISO-8859-1 -t UTF-8 CHANGELOG.md > docs/changelog/index.md

      - name: Replace the CONTRIBUTING_copy.md with the latest CONTRIBUTING.md but convert it to UTF8
        run: iconv -f ISO-8859-1 -t UTF-8 CONTRIBUTING.md > docs/contributing/index.md

      - name: Create ac conda environment
        run: conda env create -f environment.yml
      
      - name: Build the documentation
        run: conda run -n ac mkdocs build

      - run: conda run -n ac mkdocs gh-deploy --force
