name: docker-cmake-build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build-container:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        lfs: true
    - run:  git lfs pull

    - name: Build the Docker image
      run: docker build -t ac .
      