name: ubuntu-build-and-test

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build-container:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Log in to Docker Hub
        uses: docker/login-action@f4ef78c080cd8ba55a85445d5b36e214a81df20a
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build container
        run: docker build -t ghcr.io/ibois-epfl/augmented-carpentry-ubuntu-testsuite:latest ${{ github.workspace }}/tests/dockerfiles/ubuntu
      - name: Push
        run: docker push ghcr.io/ibois-epfl/augmented-carpentry-ubuntu-testsuite:latest

  configure-and-build-test:
    needs: build-container
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/ibois-epfl/augmented-carpentry-ubuntu-testsuite:latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
          submodules: true
      - name: Configure
        run: |
          git config --global --add safe.directory ${PWD}
          cmake . -B build/ -D HEADLESS_TEST=ON -D DEPLOY_ON_TOUCH=OFF
      - uses: actions/upload-artifact@v3
        if: ${{ failure() }}
        with:
          name: configure-artifacts
          path: build/
          retention-days: 1
      - name: Build and run
        run: cmake --build build
      - name: Run integration tests
        run: |
          export DISPLAY=:77
          Xvfb :77 -screen 0 800x600x24 &
          build/bin/AC tests/assets/config_smoke_test.ini
          cat tests/output/log_recorders/test/log.txt